server:
  port: 9089
logging:
  level:
    com:
      cto:
        freemarker: DEBUG
    org:
      springframework:
        web: INFO
spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://localhost:3306/base_freemarker?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    enabled: true
    suffix: .html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    password: root
    timeout: 5000

  elasticsearch:
    rest:
      uris: 127.0.0.1:7001
      username: elastic
      password: 1234566
#mybatis-plus配置
mybatis-plus:
  configuration:
    #二级缓存关闭
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto